// Random game data that is added to Firestore
// After you've signed into Best Games, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  gameNames: [
    "World of Warcraft",
    "The Legend of Zelda: Breath of the Wild",
    "The Witcher 3: Wild Hunt",
    "Red Dead Redemption 2",
    "The Last of Us",
    "Portal 2",
    "Half-Life 2",
    "Dark Souls",
    "Super Mario 64",
    "Minecraft",
    "God of War",
    "Elden Ring",
    "Hades",
    "The Elder Scrolls V: Skyrim",
    "Mass Effect 2",
    "Bloodborne",
    "Celeste",
    "Hollow Knight",
    "Final Fantasy VII",
    "Chrono Trigger",
    "Undertale",
    "Bioshock",
    "The Last of Us Part II",
    "Ghost of Tsushima",
    "Persona 5",
    "Sekiro: Shadows Die Twice",
    "Metal Gear Solid V",
    "Horizon Zero Dawn",
    "Spider-Man",
    "Stardew Valley",
  ],
  releaseYears: [
    1996,
    1998,
    2001,
    2004,
    2007,
    2010,
    2011,
    2013,
    2015,
    2016,
    2017,
    2018,
    2019,
    2020,
    2022,
  ],
  gameGenres: [
    "MMORPG",
    "Action-Adventure",
    "RPG",
    "FPS",
    "Puzzle",
    "Platformer",
    "Sandbox",
    "Strategy",
    "Sports",
    "Fighting",
    "Racing",
    "Simulation",
    "Roguelike",
    "Metroidvania",
  ],
  gameReviews: [
    { text: "An absolute masterpiece! This game changed my life.", rating: 5 },
    { text: "Perfect gameplay mechanics and incredible story!", rating: 5 },
    { text: "The best game I've ever played, hands down.", rating: 5 },
    { text: "Amazing graphics and immersive world design.", rating: 5 },
    { text: "A true gaming experience that everyone should try!", rating: 5 },
    {
      text: "Captivating story that kept me hooked for hours.",
      rating: 5,
    },
    { text: "Flawless execution and endless replayability.", rating: 5 },
    { text: "Revolutionary gameplay that set a new standard.", rating: 5 },
    { text: "Great game with solid mechanics and fun gameplay.", rating: 4 },
    { text: "Enjoyed every moment, would definitely play again.", rating: 4 },
    { text: "Engaging story with beautiful visuals.", rating: 4 },
    { text: "Good game, but could use some improvements.", rating: 3 },
    { text: "Decent gameplay, but nothing extraordinary.", rating: 3 },
    { text: "The game was average, expected more.", rating: 3 },
    {
      text: "Buggy gameplay and disappointing mechanics.",
      rating: 2,
    },
    { text: "Expected much more, but left unsatisfied.", rating: 2 },
    { text: "Underwhelming story and repetitive gameplay.", rating: 2 },
    { text: "Disappointing game overall.", rating: 2 },
    {
      text: "Terrible experience, will never play again.",
      rating: 1,
    },
    {
      text: "Worst game I've played in years.",
      rating: 1,
    },
    { text: "Avoid this game, complete waste of time.", rating: 1 },
    { text: "Frustrating controls and boring story.", rating: 1 },
    { text: "Simply outstanding! A true gaming masterpiece.", rating: 5 },
    { text: "Couldn't stop playing, absolutely addictive.", rating: 5 },
    { text: "Top-notch quality, worth every hour invested.", rating: 5 },
    { text: "Highly recommended for all gaming enthusiasts.", rating: 5 },
    { text: "Incredible game that exceeded all expectations.", rating: 5 },
    { text: "A gem of a game, perfect in every aspect.", rating: 5 },
    { text: "Excellent variety of content and gameplay.", rating: 5 },
    { text: "A fantastic gaming experience overall.", rating: 5 },
    {
      text: "Beautiful atmosphere, perfect for immersive play.",
      rating: 4,
    },
    { text: "Great gameplay, but optimization could be better.", rating: 4 },
    {
      text: "Pleasantly surprised by the depth of content.",
      rating: 4,
    },
    { text: "Well-designed levels and engaging mechanics.", rating: 4 },
    { text: "Satisfying gameplay, suitable for casual sessions.", rating: 4 },
    { text: "The game was okay, nothing special.", rating: 3 },
    {
      text: "Mechanics could be better, but playable.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the money.", rating: 2 },
    { text: "Mediocre gameplay and lackluster visuals.", rating: 2 },
    {
      text: "Regret buying such a disappointing game.",
      rating: 2,
    },
    { text: "Not up to par with my expectations.", rating: 2 },
  ],
};
